### ISSUE TITLE
using the plugin / list codes

### ISSUE THREAD

**Issue by mikeatcityuni** [tonyjbutler/moodle-mod_aspirelist#1]
Hi, not an issue as such .. just a request for more info on using the plugin specifically around list codes and linking to Moodle course codes.

First, I wonder why in the Aspire resource list configuration options you can only select ID Number or custom table for aspirelist:codesource ... shortname should be in this list as well surely.

So, we want to use shortname, but it is not clear when selecting custom database table what the field values should be and even then we would need to use regexp with those. Looks like regexp can only be used if ID Number was used as aspirelist:codesource.

For info our shortnames are in form MODULE_PERIOD_OCCURENCE_YEAR

Can anyone clarify the process of linking to Aspire list codes? Are we forced to use the ID Number field for our purposes?

**Comment by tonyjbutler** [comment]
Hi Mike,

The only reason shortname is not currently an option is because no-one had suggested it yet. I'll look into including it in the next version. I included idnumber because this was already used in the Moodle block plugin developed by Talis (and because it is the recommended column in the course table for storing ID numbers from external systems) and the custom table option simply because that's what we use here: an additional table in the Moodle database which is populated by our SIS sync script with a simple mapping between Moodle course IDs and Talis codes.

Currently the regex option only applies to idnumber because I envisioned that if a separate table was being populated with Talis codes by a custom script, then it would be unlikely to contain anything else. Are you unable to use idnumber because it already contains something else, or is it just that you are unable to get it automatically populated without changes to your sync scripts?

I will look into including shortname as a code source in the next version, and enabling regex matching for it, but in the meantime, one option that does spring to mind for you is this: why not just create a view in your Moodle database that maps mdl_course.id (for example) against the Talis code portion of your shortnames (extracted using whatever pattern matching function is provided by your database), and then configure the plugin to use the view as a custom table for the code source.

Hope this helps, and let me know how you get on with the suggestion above.

Cheers,
Tony

**Comment by mikeatcityuni** [comment]
Hi Tony, thanks that all makes perfect sense. 

We just need a solution that has as few moving parts as possible so for us being able to reference and use regex on shortname would be ideal. We can't easily get data into idnumber and anyway, we are currently re-purposing that field for a course 'alias' which is displayed on the course pages as title. Again, we _could_ create the view and do it via a custom table but it would entail more 'moving parts' to ensure that table had correct data in year after year. 

Thanks for your offer to put shortname as option in next release - much appreciated. Any idea of timelines?

mike

**Comment by tonyjbutler** [comment]
The beauty of a view is that it would automatically stay in sync with your course table so you wouldn't have to worry about it containing out-of-date data. However if you'd prefer to hold on, there will be a new release for Moodle 2.9 in May so I'll make sure it's in by then at the latest.

Cheers,
Tony

**Comment by mikeatcityuni** [comment]
Hi, but how do the readling list codes get in to the custom table? Or do you mean the view constructs what it thinks _should_ be the codes based on some regexp SQL of shortname? I'm a bit confused about how different lists for different years are accessed via this method. For idnumber you have a regexp setting for year? Since we keep multiple years of courses in our Moodle we'd need each course to link to correct year's list.

**Comment by tonyjbutler** [comment]
That's right. The query you run to create the view will contain a regex pattern to extract the list code from the shortname field for each course, and map it against the course id or some other unique value. I can help you with this if you give me an example shortname, its corresponding list code and the type of database you use for Moodle.

You don't really need to worry about the year code, although I'll include the option to get this from the shortname in the next release too. If a year code isn't specified the module config form just presents the teacher with the latest list that matches the given code(s). Once an instance has been configured, the GUID of the list used is stored in the database against each list item, so lists in courses from previous years will continue to display the correct data. The only reason you would need to specify a year code would be if you needed to re-configure a module instance from a previous year and force it to continue using the old version of the list.

**Comment by mikeatcityuni** [comment]
OK ... I read somewhere you can't use regexp in MySQL to split strings and so I was put off ... if you can help with the view SQL then we could test it out.

So, our 'shortname' codes are in form ....

SMM001_PRD1_A_2014-15

where SMM001 is module code and Talis code, PRD1 is academic period, A is occurrence and 2014-15 is year, always separated by underscore. So, we'd need only the first part for Aspire though it might be useful to be able to split these into four fields one for each 'module', 'period', 'occurrence' and 'year' - might be useful for other things.

Our database is MySQL 5.6.19 on RHEL6

Cheers and thanks

**Comment by tonyjbutler** [comment]
You're right, REGEXP can't be used to extract substrings, but fortunately there are other functions we can use. Assuming the data itself will never contain underscores, and that you use the default 'mdl_' table prefix, the following should (hopefully) work:

```
CREATE VIEW course_details AS
SELECT id,
SUBSTRING_INDEX(shortname, '_', 1) AS module,
SUBSTRING_INDEX(SUBSTRING_INDEX(shortname, '_', 2), '_', -1) AS period,
SUBSTRING_INDEX(SUBSTRING_INDEX(shortname, '_', -2), '_', 1) AS occurrence,
SUBSTRING_INDEX(shortname, '_', -1) AS year
FROM mdl_course
WHERE id <> 1
ORDER BY id ASC;
```

**Comment by mikeatcityuni** [comment]
Hi, if we wanted to use ID number for now but it contained the full title "MU1065 Composition 1 (PRD2 A 2014/15)" what regexp would we need to use to get just the code from before the first space i.e. MU1065?

**Comment by tonyjbutler** [comment]
Did the code I posted above to create a view not work?

**Comment by mikeatcityuni** [comment]
Hi, yes thanks ...  the view stuff is great for testing but I can't get it on LIVE quickly (got to go through change board etc). I wanted to demo the plugin on our live system and using ID number with the full title is the only way to do it - I could paste the module code into ID Number but as I said we are currently using that as the title of the page and it would look odd. Cheers

**Comment by tonyjbutler** [comment]
Do the module codes always follow the same pattern e.g. 2 letters followed by 4 numbers? What's the general format that always applies no matter what?

**Comment by mikeatcityuni** [comment]
Hi, in that format they are always at the start of the string followed by a space and either XXNNNN or XXXNNN

**Comment by tonyjbutler** [comment]
Try /^([A-Z]{2}[0-9]{4})|([A-Z]{3}[0-9]{3})/ with a few different examples.

**Comment by mikeatcityuni** [comment]
Hi, great that works thanks ... regexp has always been my nemesis!
OK so that allows us to demo this feature (which everyone loves by the way) but long term we would like the ability to set up config to use regexp on shortname field too. Cheers

**Comment by tonyjbutler** [comment]
No problem. I'll let you know when the next release is available.

Cheers,
Tony

**Comment by tonyjbutler** [comment]
Hi Mike,

I've made the changes to allow shortname to be used as the source for Aspire list codes and year codes, including regex support. It seems to work OK but I'd appreciate it if you could give it a test. You can download the source from https://github.com/tonyjbutler/moodle-mod_aspirelist/archive/master.zip.

Cheers,
Tony

**Comment by mikeatcityuni** [comment]
many thanks Tony, will give it a try. We are just setting up a TEST 2.8 environment - it should work with that right?

**Comment by tonyjbutler** [comment]
Yes it should work with 2.7 and 2.8.

**Comment by tonyjbutler** [comment]
Hi Mike,

Did this work as expected? I'm about to do a stable release for Moodle 2.9.

Cheers,
Tony

**Comment by mikeatcityuni** [comment]
yes all good thanks

**Comment by tonyjbutler** [comment]
This has been included in release 2.9.0 which is now available for download at https://moodle.org/plugins/pluginversion.php?id=8607 (or checkout the MOODLE_29_STABLE branch from this repository).

**Comment by mikeatcityuni** [comment]
Hi, the changes you mentioned above to allow use of shortname ... are not in release for 2.8! Gah!

**Comment by tonyjbutler** [comment]
No, it's a new feature so it's just in the new release. Won't you be upgrading to Moodle 2.9 over the summer?

If not, it's just a single commit (https://github.com/tonyjbutler/moodle-mod_aspirelist/commit/2b4a1c726169bf7f39461f6e189ba00941fef481) so you could always cherry-pick it.

**Comment by mikeatcityuni** [comment]
2.8 :-( ... Ok will cherry pick the code I need
