### ISSUE TITLE
Section headings not showing

### ISSUE THREAD

**Issue by mikeatcityuni** [tonyjbutler/moodle-mod_aspirelist#4]
When items from any section are selected to show either inline or as a separate page they are not shown with their section headings. Not sure if they should be showing so this may be either a feature request or a bug report!

**Comment by tonyjbutler** [comment]
They should be showing. This seems to be a side effect of the changes Talis made to the list structure to fix https://github.com/tonyjbutler/moodle-mod_aspirelist/issues/3.

Fortunately I've managed to fix it with a change to the plugin, which I've already pushed and tagged as new releases in the MOODLE_29_STABLE and MOODLE_27_STABLE branches here. I'll update the plugins directory on moodle.org with the new releases after lunch.

**Comment by mikeatcityuni** [comment]
ah ok, sorry thought that was unrelated, we've got an update to our Moodle on Friday - last one before term starts proper so I'll try and cherry pick fix for our 2.8 code. Can you send me a link to the commit?

**Comment by tonyjbutler** [comment]
No worries. I've backported it to the MOODLE_27_STABLE branch (which also supports Moodle 2.8.x) so you should be able to just pull or rebase. However if you'd rather cherry-pick, the commit is https://github.com/tonyjbutler/moodle-mod_aspirelist/commit/40ffabce62b5fb292f8a417c9e3d37297d8a7a5e.

**Comment by mikeatcityuni** [comment]
if I recall though the change you did for issue #1 wasn't back ported was it, I had to cherry pick that.

**Comment by tonyjbutler** [comment]
That's right, but it shouldn't present a problem for Git. Assuming you're on the MOODLE_27_STABLE branch and the remote is named 'origin', you can just do a 'git fetch origin' followed by a 'git rebase origin/MOODLE_27_STABLE'.

Your branch will be updated and the cherry-picked commit will be re-applied on top again.
