### ISSUE TITLE
link to Online Resource where that is a scanned item is broken

### ISSUE THREAD

**Issue by mikeatcityuni** [tonyjbutler/moodle-mod_aspirelist#5]
We have a list where there are scanned items. Where a link is added via the activity it appears correctly, the link to item is correct but link to Online Resource shows malformed URL.

![reading_list_issue_online_resource](https://cloud.githubusercontent.com/assets/4233765/10458986/61ac08da-71c5-11e5-807c-6c283672100b.JPG)

link 1 opens nicely in popup
http://readinglists.city.ac.uk/items/FC1AC33F-FAF8-5777-68CD-2CBCC58D796E.html?referrer=%2Flists%2F81CDA36C-C97A-5C42-E764-FBECAB7468AF.html%23item-FC1AC33F-FAF8-5777-68CD-2CBCC58D796E 

link 2 is shown as:
http://readinglists.city.ac.uk/http://readinglists.city.ac.uk/items/FC1AC33F-FAF8-5777-68CD-2CBCC58D796E

**Comment by tonyjbutler** [comment]
I'm blaming Talis for this, with their inconsistent format for these links depending on the type of resource (one format for TADC resources, another for everything else).

This was fixed in the last release (https://github.com/tonyjbutler/moodle-mod_aspirelist/releases/tag/v2.7.7 for you I think).
