### ISSUE TITLE
activity stopped working where list has no structure

### ISSUE THREAD

**Issue by mikeatcityuni** [tonyjbutler/moodle-mod_aspirelist#6]
Hi,

not sure if this is a known issue or intended behaviour (nothing indicated in readme) but if a list has no structure - is just a list of items - then the activity doesn't find anything, just returns message "Sorry, there are no resource lists associated with this module." Our other lists all seem to be fine, I have found 2 so far which fail for this reason.

Mike

**Comment by tonyjbutler** [comment]
Hi Mike,

When you say "activity stopped working" does this mean that it used to work OK for these lists, but now it doesn't? Could you provide links to these two lists please? Finally, which release of mod_aspirelist are you using?

Thanks,
Tony

**Comment by mikeatcityuni** [comment]
Hi, actually I'm not sure that it ever worked for lists with no sections ... it's quite hard to find them. I actually found this by accident, just pulled up a recently edited list to demo the activity and it was broke!

here's 2 lists that are not working:
http://readinglists.city.ac.uk/lists/98DC2105-3E6E-69AB-D54A-D7695DF97B78.html
http://readinglists.city.ac.uk/lists/0BA8C80C-1C58-5A00-999D-0815C18759DC.html

we're using 2.9.5 (Build: 20160525)

**Comment by tonyjbutler** [comment]
No, they work fine for me:
![jom275](https://cloud.githubusercontent.com/assets/1395170/18882340/bda8e6ce-84d6-11e6-9812-9370745e2eba.png)

Maybe you have a misconfiguration.

Cheers,
Tony

**Comment by mikeatcityuni** [comment]
Hi, this is weird. This list just won't show up for me but others do. Is there any cacheing done ... if I add a section on reading list should it appear instantly in activity?

**Comment by tonyjbutler** [comment]
Yes, list data is cached for performance, but the cached data is only used when viewing the list. For the list editing form the latest data is always loaded.

**Comment by mikeatcityuni** [comment]
OK, so am on test system now, there are just certain lists that we can link to from Moodle using our custom dashboard using API but the activity just shows nothing, says  "Sorry, there are no resource lists associated with this module." Wondering how I can troubleshoot this ... we know the lists are OK cos you can get them to work, so what else could it be?

**Comment by tonyjbutler** [comment]
Did you check the config (both the course settings and the mod_aspirelist admin settings)?

I would start by verifying that the course idnumber/shortname (whichever you've configured to contain the module code) matches your module code regex (assuming you've configured one).

**Comment by mikeatcityuni** [comment]
Hi, well we've not changed anything but looking at last years modules I think I have it .... NO module with a code XXXNNN is getting picked up only XXNNNN, seems no-one tried to use this last year with a XXXNNN module 

Just to say ... postgrad courses have form XXXNNN (e.g. JOM275) and undergrad courses XXNNNN (e.g. JO1204

Our coderegex is:
/([A-Z]{2}[0-9]{4})|([A-Z]{3}[0-9]{3})/

yearregex is /([0-9]{4}-[0-9]{2})$/

this should be right no?

**Comment by mikeatcityuni** [comment]
https://regex101.com/r/FubhIq/1

**Comment by tonyjbutler** [comment]
Does that not work?

**Comment by mikeatcityuni** [comment]
should work but apparently it does not!

**Comment by mikeatcityuni** [comment]
Ok so it looks like only the first part of the regex is being used, is our syntax wrong then? If I swap around to /([A-Z]{3}[0-9]{3})|([A-Z]{2}[0-9]{4})/
then now the XXXNNN modules are getting picked up but not the XXNNNN

**Comment by tonyjbutler** [comment]
Try this:
/^([A-Z]{2,3}[0-9]{3,4})/

**Comment by mikeatcityuni** [comment]
YES! That's it. What's up there then? That was expensive bit of regexp!

**Comment by tonyjbutler** [comment]
I think the code only returns full matches (as many as it can find) or the first parenthesized subpattern match found. So /[A-Z]{3}[0-9]{3}|[A-Z]{2}[0-9]{4}/ would work because it's always going to match the full pattern, but when you introduce subpatterns with /([A-Z]{3}[0-9]{3})|([A-Z]{2}[0-9]{4})/ it will only capture the first one.

Anyway, glad we got it sorted.
