### ISSUE TITLE
https ready?

### ISSUE THREAD

**Issue by mikeatcityuni** [tonyjbutler/moodle-mod_aspirelist#7]
Hi, we are going to switch to https soon - can you confirm your plugin works with https, I assume we just need to change URL in config settings.

Cheers
Mike

**Comment by tonyjbutler** [comment]
Yes, it does for us. All the recent releases from 2.9 onwards have an additional field in the admin config form for the HTTPS alias. It's important to keep the base (HTTP) URL configured too though, as this is still used by the API, even for HTTPS sites. See the screenshot of our config.
![aspire_https](https://user-images.githubusercontent.com/1395170/26889495-487ddf70-4ba6-11e7-98eb-9c5972605486.png)
